// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-r2o1dize-1rtMX1KoZGlW5N-NeJaZ4E',
    appId: '1:501313773643:web:33fdac93b35ca72226adce',
    messagingSenderId: '501313773643',
    projectId: 'morocco-explorer',
    authDomain: 'morocco-explorer.firebaseapp.com',
    storageBucket: 'morocco-explorer.appspot.com',
    measurementId: 'G-1BTLNJR348',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWsPS4m9Q1h6XlGlp5W8KQ4UgEnKNvM7Y',
    appId: '1:501313773643:android:36140e0adf43f69326adce',
    messagingSenderId: '501313773643',
    projectId: 'morocco-explorer',
    storageBucket: 'morocco-explorer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgOEEKyGHNx9hbS23lpeGGUl_pqGTkhig',
    appId: '1:501313773643:ios:3ccff6f164b8561826adce',
    messagingSenderId: '501313773643',
    projectId: 'morocco-explorer',
    storageBucket: 'morocco-explorer.appspot.com',
    iosClientId: '501313773643-1avu5snl8td8jii9mrsqle9a6c63u397.apps.googleusercontent.com',
    iosBundleId: 'com.example.moroccanExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgOEEKyGHNx9hbS23lpeGGUl_pqGTkhig',
    appId: '1:501313773643:ios:ea1480d47e68013526adce',
    messagingSenderId: '501313773643',
    projectId: 'morocco-explorer',
    storageBucket: 'morocco-explorer.appspot.com',
    iosClientId: '501313773643-da4k8t24827b8g30s24uk73kob7k4d1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.moroccanExplorer.RunnerTests',
  );
}
